<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
    	<li class="level0 level-top home"><a class="level-top" href="<?php echo $this->getUrl('') ?>">Home</a></li>
        <?= /* @noEscape */ $_menuHtml?>
        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('top-navigation-links')->toHtml(); ?>
        <?= $block->getChildHtml() ?>
    </ul>
</nav>