<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
?>
<?php //$helper = $this->helper('Srp\Base\Helper\Data');?>

<?php //echo $block->getViewFileUrl(''); ?>
<div class="container justified">
    <div class="row">        
        <div class="col-12 col-xs-12 col-sm-12 col-md-12 col-lg-4 search-box">
          <?php echo $block->getChildHtml('topSearch');?>
        </div>
        <div class="col-12 col-xs-12 col-sm-12 col-md-12 col-lg-4 header-left logo-main">
          <?php echo $block->getChildHtml('logo');?>
        </div>
    <div class="col-12 col-xs-12 col-sm-12 col-md-3 col-lg-4 header-right">      
        <ul class="customer-links">
              <li class="nav-item">
                <span data-bind="scope: 'wishlist'" class="customer-wishlist">
                  <a class="nav-link" href="<?php echo $this->getUrl('wishlist') ?>">
                    <!-- ko if: wishlist().counter --><span data-bind="text: wishlist().counter" class="counter qty"></span><!-- /ko -->
                  </a>
                </span>
              </li> 
              <li class="nav-item login">
                <a href="<?php echo $this->getUrl('customer/account/login') ?>"></a> 
                <?php echo $block->getChildHtml('top.links');?>
              </li> 
          </ul>
          <?php echo $block->getChildHtml('minicart');?>
    </div>
    </div>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "wishlist": {
                    "component": "Magento_Wishlist/js/view/wishlist"
                }
            }
        }
    }
}
</script>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "customer": {
                    "component": "Magento_Customer/js/view/customer"
                }
            }
        }
    }
}
</script>