<form id="share-cart-sms-form" class="share-cart-form" style="display: none" action="<?=/* @noEscape */$block->getHelper()->prepareUrl('share_cart/action/sms') ?>" method="post">
    <?=/* @noEscape */$block->getBlockHtml('formkey'); ?>
    <?php if ($block->getIsCaptchaEnabled()) :?>
        <input type="hidden" name="g-recaptcha-response" value="">
    <?php endif;?>
    <fieldset class="fieldset">
        <div class="field required">
            <label for="recipient_number"><?=/* @noEscape */__("Recipient Number (including country code)") ?></label>
            <div class="control">
                <input class="input-text required-entry" id="recipient_number" name="recipient_number" placeholder="<?=/* @noEscape */__("Enter Mobile Number")?>" value="<?=/* @noEscape */$block->escapeHtml($block->getRecipientNumber()) ?>" />
            </div>
        </div>
        <?php if (!$block->getIsLoggedIn()) :?>
            <div class="field required">
                <label for="sender_name"><?=/* @noEscape */__("Your Name") ?></label>
                <div class="control">
                    <input class="input-text required-entry"  name="sender_name" placeholder="<?=/* @noEscape */__("Enter Your Name")?>" value="<?=/* @noEscape */$block->escapeHtml($block->getSenderName()) ?>" />
                </div>
            </div>
            <div class="field required">
                <label for="sender_email"><?=/* @noEscape */__("Your Email") ?></label>
                <div class="control">
                    <input class="input-text required-entry validate-email"  name="sender_email" placeholder="<?=/* @noEscape */__("Enter Your Email")?>" value="<?=/* @noEscape */$block->escapeHtml($block->getSenderEmail()) ?>" />
                </div>
            </div>
        <?php endif;?>
    </fieldset>
    <div class="result" style="display:none;"></div>
    <div class="actions-toolbar">
        <button type="submit" title="<?=/* @noEscape */__('Share') ?>" class="button2" value="<?=/* @noEscape */__('Share') ?>">
            <span>
                <span data-processing-text="<?=/* @noEscape */__('Sending SMS. Please wait..') ?>">
                    <?=/* @noEscape */__('Share') ?>
                </span>
            </span>
        </button>
    </div>
</form>