<form id="share-cart-whatsapp-form" class="share-cart-form" style="display: none" action="<?=/* @noEscape */$block->getHelper()->prepareUrl('share_cart/action/whatsApp')?>" method="post">
    <?=/* @noEscape */$block->getBlockHtml('formkey')?>
    <?php if ($block->getIsCaptchaEnabled()) :?>
        <input type="hidden" name="g-recaptcha-response" value="">
    <?php endif;?>
    <?php if (!$block->getIsLoggedIn()) :?>
        <fieldset class="fieldset">
            <div class="field required">
                <label for="sender_name"><?=/* @noEscape */__("Your Name") ?></label>
                <div class="control">
                    <input class="input-text required-entry"  name="sender_name" placeholder="<?=/* @noEscape */__("Enter Your Name")?>" value="<?=/* @noEscape */$block->escapeHtml($block->getSenderName()) ?>" />
                </div>
            </div>
            <div class="field required">
                <label for="sender_email"><?=/* @noEscape */__("Your Email") ?></label>
                <div class="control">
                    <input class="input-text required-entry validate-email  "  name="sender_email" placeholder="<?=/* @noEscape */__("Enter Your Email")?>" value="<?=/* @noEscape */$block->escapeHtml($block->getSenderEmail()) ?>" />
                </div>
            </div>
        </fieldset>
    <?php endif;?>
    <div class="result" style="display:none;"></div>
    <div class="actions-toolbar">
        <button type="submit" title="<?=/* @noEscape */__('Prepare Cart to Share') ?>" class="button2" value="<?=/* @noEscape */__('Prepare Cart to Share') ?>">
            <span>
                <span data-processing-text="<?=/* @noEscape */__('Processing. Please wait..') ?>">
                    <?=/* @noEscape */__('Prepare Cart to Share') ?>
                </span>
            </span>
        </button>
    </div>
</form>