

<section class="overview sign-in-sign-up">
   <div class="container">
      <div class="row">
         <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 right-side">
            <?php echo $block->getChildHtml('customer_form_login');?>
         </div>
         <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 first-side">
            <?php echo $block->getChildHtml('customer_form_register');?>
         </div>
      </div>
   </div>
</section>